api_platform:
    title: Hello API Platform
    version: 1.0.0
    enable_docs: true
    enable_profiler: false
    enable_swagger_ui: true
    enable_re_doc: true
    enable_entrypoint: true
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']  # Ajouter cette ligne pour accepter application/json
    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
    keep_legacy_inflector: false
    use_symfony_listeners: true
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    show_webby: false
    eager_loading:
        max_joins: 50  # Augmente la limite ici (par défaut c'est 30)
