framework:
    secret: '%env(APP_SECRET)%'
    # csrf_protection: true

    # Note that the session will be started ONLY if you read or write from it.
    default_locale: fr
    trusted_proxies: '127.0.0.1'
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

    # esi: true
    # fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
