gesdinet_jwt_refresh_token:
    refresh_token_class: App\Entity\RefreshToken
    ttl: 2592000  # Durée de validité du refresh token en secondes (par ex. 30 jours)
    ttl_update: false
    firewall: api
    user_provider: app_user_provider
