security:
    # Gestion des hachages de mot de passe pour les utilisateurs
    password_hashers:
        App\Entity\Utilisateur: 'auto'

    # Définir le fournisseur d'utilisateurs pour utiliser l'entité Utilisateur
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email

    firewalls:
        # Firewall pour l'environnement de développement
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Firewall pour la connexion
        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login_check
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        # Firewall dédié à la régénération des tokens
        refresh_jwt:
            pattern: ^/api/token/refresh
            stateless: true
            refresh_jwt:
                check_path: /api/token/refresh

        api:
            pattern: ^/api
            stateless: true
            jwt: ~

    access_control:
        - { path: ^/api/utilisateurs/me, roles: IS_AUTHENTICATED_FULLY, methods: [GET] }
        - { path: ^/api/utilisateurs/\d+, roles: IS_AUTHENTICATED_FULLY, methods: [GET, PUT, PATCH, DELETE] }
        - { path: ^/api/paniers/add-product, roles: IS_AUTHENTICATED_FULLY, methods: [POST] }
        - { path: ^/api/paniers/\d+/decrement-product, roles: IS_AUTHENTICATED_FULLY, methods: [PATCH] }
        - { path: ^/api/paniers/\d+/increment-product, roles: IS_AUTHENTICATED_FULLY, methods: [PATCH] }
        - { path: ^/api/favoriss , roles: IS_AUTHENTICATED_FULLY, methods: [GET, POST, DELETE] }
        - { path: ^/api/produits, roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/api/produits/\d+, roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/api/utilisateurs, roles: PUBLIC_ACCESS, methods: [POST] }
        - { path: ^/api/login, roles: PUBLIC_ACCESS, methods: [POST] }
        - { path: ^/api/(login|token/refresh), roles: PUBLIC_ACCESS }
        - { path: ^/api/password-reset-request, roles: PUBLIC_ACCESS, methods: [POST] }
        - { path: ^/api/password-reset, roles: PUBLIC_ACCESS, methods: [POST] }
        - { path: ^/api/docs, roles: PUBLIC_ACCESS }
        - { path: ^/api/categories, roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/api/categories/\d+, roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
