controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

jwt_login:
    path: /api/login_check
    methods: [POST]
    controller: Lexik\Bundle\JWTAuthenticationBundle\Controller\AuthenticationController::login

api_refresh_token:
    path: /api/token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh
    methods: [POST]

mail_test:
    path: /send-test-email
    controller: App\Controller\MailController::sendEmail
